name: docker-build-workflow

on:
  push:
    branches: [ main,master ] #none # 
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      working-directory: helloworld-demo-python
      run: docker build . --file Dockerfile --tag helloworld-demo-python:$(date +%s)